[package]
name = "canvas_cli_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.197"
thiserror = "1.0.57"
toml = "0.8.10"
