[package]
name = "canvas_auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
keyring = "2.3.2"
oauth2 = "4.4.2"
thiserror = "1.0.57"
